# This workflow will to Production
name: Production
on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
jobs:
  deploy:
    name: Production Stage
    permissions: write-all
    uses: 
      mustcompany/mustcompany-workflows/.github/workflows/must-pirateship-pipeline.yaml@release
    with:
      environment: production
      version: ${{ inputs.version }}
    secrets: inherit
