name: Quality Check
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - '*patch'
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  call:
    if: github.actor != vars.SERVICE_USERNAME
    name: Quality Check
    permissions: write-all
    uses: mustcompany/mustcompany-workflows/.github/workflows/must-pirateship-quality-check.yaml@release
    secrets: inherit
